function populate(s1, s2) {
    s1 = document.getElementById(s1);
    s2 = document.getElementById(s2);

    s2.innerHTML = "";

    if (s1.value == "ACCOMODATION AND FOOD SERVIVES ACTIVITIES") {
        var optionArr = [
            "|Select Classification 2",
            "ACCOMMODATION|ACCOMMODATION",
            "BAKERY SERVICES|BAKERY SERVICES",
            "BREWERY SERVICES|BREWERY SERVICES",
            "DEAL IN HOT DRINKS|DEAL IN HOT DRINKS",
            "DEAL IN SOFT DRINKS|DEAL IN SOFT DRINKS",
            "DEAL IN WINES, DRINKS AND BEVERAGES|DEAL IN WINES, DRINKS AND BEVERAGES",
            "FOOD AND BEVERAGES SERVICES ACTIVITIES|FOOD AND BEVERAGES SERVICES ACTIVITIES",
            "FRUITS / FRUIT JUICE PRODUCTION AND SALES|FRUITS / FRUIT JUICE PRODUCTION AND SALES",
            "HOTEL RESERVATION SERVICES|HOTEL RESERVATION SERVICES",
            "HOTEL AND HOSPITALITY|HOTEL AND HOSPITALITY",
            "HOTEL/HOSPITALITY SERVICES|HOTEL/HOSPITALITY SERVICES",
            "OPERATE CONFECTIONERY SHOP|OPERATE CONFECTIONERY SHOP",
            "OPERATE FAST FOOD OUTLET|OPERATE FAST FOOD OUTLET",
            "OPERATE RESTAURANT AND CATERING SERVICES|OPERATE RESTAURANT AND CATERING SERVICES",
            "OPERATE VIEWING CENTRE|OPERATE VIEWING CENTRE"
        ];
    }

    else if (s1.value == "ACTIVITIES OF EXTRATERRITORIAL ORGANISATION AND BODIES") {
        optionArr = [
            "|Select Classification 2",
            "ACTIVITIES OF EXTRATERRITORIAL ORGANIZATIONS AND BODIES|ACTIVITIES OF EXTRATERRITORIAL ORGANIZATIONS AND BODIES"
        ];
    }

    else if (s1.value == "ACTIVITIES OF HOUSE AS EMPLOYMENT UNDIFFERENTIATED GOODS-AND SERVICES-PRODUCING ACTIVITIES OF HOUSEHOLDS FOR OWN USE") {
        optionArr = [
            "|Select Classification 2",
            "ACTIVITIES OF HOUSEHOLDS AS EMPLOYERS OF DOMESTIC PERSONNEL|ACTIVITIES OF HOUSEHOLDS AS EMPLOYERS OF DOMESTIC PERSONNEL",
            "UNDIFFERENTIATED GOODS-AND SERVICES-PRODUCING ACTIVITIES OF PRIVATE HOUSEHOLDS FOR OWN USE|UNDIFFERENTIATED GOODS-AND SERVICES-PRODUCING ACTIVITIES OF PRIVATE HOUSEHOLDS FOR OWN USE"
        ];
    }

    else if (s1.value == "ADMINISTRATIVE AND SUPPORT SERVICES ACTIVITIES") {
        optionArr = [
            "|Select Classification 2",
            "ABATTOIR AND MEAT SELLING SERVICES|ABATTOIR AND MEAT SELLING SERVICES|ABATTOIR AND MEAT SELLING SERVICES|ABATTOIR AND MEAT SELLING SERVICES",
            "AUTOMATED CAR WASH SERVICES|AUTOMATED CAR WASH SERVICES",
            "BLACK SMITH SERVICES|BLACK SMITH SERVICES",
            "BLOCK INDUSTRY|BLOCK INDUSTRY",
            "BOUTIQUE SERVICES|BOUTIQUE SERVICES",
            "CAR WASH SERVICES|CAR WASH SERVICES",
            "CATERING SERVICES|CATERING SERVICES",
            "CLEARING AND FORWARDING SERVICES|CLEARING AND FORWARDING SERVICES",
            "COBBLER SERVICES|COBBLER SERVICES",
            "COLD ROOM SERVICES|COLD ROOM SERVICES",
            "COMMISSION AGENCY|COMMISSION AGENCY",
            "CYBERCAFÉ AND BUSINESS CENTRE|CYBERCAFÉ AND BUSINESS CENTRE",
            "DEAL IN JEWELRY AND ACCESSORIES|DEAL IN JEWELRY AND ACCESSORIES",
            "DOMESTIC SUPPORT SERVICES|DOMESTIC SUPPORT SERVICES",
            "DRIVING SCHOOL SERVICES|DRIVING SCHOOL SERVICES",
            "EVENTS MANAGEMENT, GENERAL MERCHANDISE, WHOLESALE AND RETAIL TRADE|EVENTS MANAGEMENT, GENERAL MERCHANDISE, WHOLESALE AND RETAIL TRADE",
            "ELECTRICAL SERVICES|ELECTRICAL SERVICES",
            "EMPLOYMENT AGENCY|EMPLOYMENT AGENCY",
            "EMPLOYMENT ACTIVITIES|EMPLOYMENT ACTIVITIES",
            "ERRAND AND HOME DELIVERY SERVICES|ERRAND AND HOME DELIVERY SERVICES",
            "FARMING|FARMING",
            "FASHION DESIGNING/ TAILORING SERVICES|FASHION DESIGNING/ TAILORING SERVICES",
            "FIRE AND SAFETY SERVICES|FIRE AND SAFETY SERVICES",
            "FROZEN FOODS SERVICES|FROZEN FOODS SERVICES",
            "GENERAL CONTRACTS|GENERAL CONTRACTS",
            "GENERAL MERCHANDISE|GENERAL MERCHANDISE",
            "GOLD SMITING SERVICES|GOLD SMITING SERVICES",
            "HAT MAKING SERVICES|HAT MAKING SERVICES",
            "INDUSTRIAL CHEMICAL SERVICES|INDUSTRIAL CHEMICAL SERVICES",
            "INDUSTRIAL AND SAFETY EQUIPMENT SERVICES|INDUSTRIAL AND SAFETY EQUIPMENT SERVICES",
            "INDUSTRIAL AND SAFETY SERVICES|INDUSTRIAL AND SAFETY SERVICES",
            "INTERIOR/EXTERIOR DECORATION SERVICES|INTERIOR/EXTERIOR DECORATION SERVICES",
            "INTERNET SERVICES|INTERNET SERVICES",
            "LAUNDRY SERVICES|LAUNDRY SERVICES",
            "LUBRICANT / OIL SERVICES|LUBRICANT / OIL SERVICES",
            "MAINTENANCE AND REPAIR OF REFRIGERATOR AND AIR CONDITION|MAINTENANCE AND REPAIR OF REFRIGERATOR AND AIR CONDITION",
            "MANUFACTURER’S REPRESENTATION|MANUFACTURER’S REPRESENTATION",
            "MANUFACTURING SERVICES|MANUFACTURING SERVICES",
            "MARKETING SERVICES|MARKETING SERVICES",
            "MEDICAL LABORATORY SERVICES|MEDICAL LABORATORY SERVICES",
            "MORTUARY AND FUNERAL SERVICES|MORTUARY AND FUNERAL SERVICES",
            "OFFICE ADMINISTRATIVE,OFFICE SUPPORT AND OTHER BUSINESS SUPPORT ACTIVITIES|OFFICE ADMINISTRATIVE,OFFICE SUPPORT AND OTHER BUSINESS SUPPORT ACTIVITIES",
            "PLANT AND EQUIPMENT MANAGEMENT|PLANT AND EQUIPMENT MANAGEMENT",
            "PLASTIC MANUFACTURING SERVICES|PLASTIC MANUFACTURING SERVICES",
            "PLUMBING SERVICES|PLUMBING SERVICES",
            "PRINTING PRESS|PRINTING PRESS",
            "PRODUCTION AND SALES OF FOOTWEAR|PRODUCTION AND SALES OF FOOTWEAR",
            "PRODUCTION/SALES OF CERAMICS AND TILES|PRODUCTION/SALES OF CERAMICS AND TILES",
            "PUBLIC RELATION SERVICES|PUBLIC RELATION SERVICES",
            "RENTAL SERVICES|RENTAL SERVICES",
            "RENTAL AND LEASING ACTIVITIES|RENTAL AND LEASING ACTIVITIES",
            "RESTAURANT|RESTAURANT",
            "SAFETY EQUIPMENT SERVICES|SAFETY EQUIPMENT SERVICES",
            "SALE OF PETROLEUM PRODUCTS|SALE OF PETROLEUM PRODUCTS",
            "SALES AND SUPPLY OF IRON SEALS AND METALS|SALES AND SUPPLY OF IRON SEALS AND METALS",
            "SALES OF BOOKS AND STATIONERIES|SALES OF BOOKS AND STATIONERIES",
            "SAWMILLING SERVICES|SAWMILLING SERVICES",
            "SECURITY AND INVESTIGATION ACTIVITIES|SECURITY AND INVESTIGATION ACTIVITIES",
            "SERVICE TO BUILDING AND LANDSCAPE ACTIVITIES|SERVICE TO BUILDING AND LANDSCAPE ACTIVITIES",
            "SUPPLY OF IRON SCRAPS AND METALS|SUPPLY OF IRON SCRAPS AND METALS",
            "SUPPLY OF UNSKILLED LABOUR|SUPPLY OF UNSKILLED LABOUR",
            "TECHNICAL SERVICES|TECHNICAL SERVICES",
            "TEXTILE SERVICES|TEXTILE SERVICES",
            "TRADING|TRADING",
            "TRAVEL AGENCY|TRAVEL AGENCY",
            "TRAVEL AGENCY, TOUR OPERATOR AND OTHER RESERVATION SERVICES AND RELATED ACTIVITIES|TRAVEL AGENCY, TOUR OPERATOR AND OTHER RESERVATION SERVICES AND RELATED ACTIVITIES",
            "UPHOLSTERY AND FURNITURE MAKING|UPHOLSTERY AND FURNITURE MAKING",
            "VULCANIZING SERVICES|VULCANIZING SERVICES",
            "WELDING SERVICES|WELDING SERVICES",
            "WHEEL BALANCING AND ALIGNMENT SERVICES|WHEEL BALANCING AND ALIGNMENT SERVICES"
        ];
    }

    else if (s1.value == "ART, ENTERTAINMENT AND RECREATION") {
        optionArr = [
            "|Select Classification 2",
            "ART GALLERIES, MUSEUM AND MONUMENTS SERVICES|ART GALLERIES, MUSEUM AND MONUMENTS SERVICES",
            "ARTISTE MANAGEMENT AND SERVICES|ARTISTE MANAGEMENT AND SERVICES",
            "ARTS, CRAFT, AND DESIGNING|ARTS, CRAFT, AND DESIGNING",
            "BAR SERVICES|BAR SERVICES",
            "CREATIVE, ART AND ENTERTAINMENT ACTIVITIES|CREATIVE, ART AND ENTERTAINMENT ACTIVITIES",
            "ENTERTAINMENT SERVICES|ENTERTAINMENT SERVICES",
            "EVENTS MANAGEMENTS/PLANNING|EVENTS MANAGEMENTS/PLANNING",
            "GAMBLING AND BETTING ACTIVITIES|GAMBLING AND BETTING ACTIVITIES",
            "INSTALLATION OF CCTV AND ALLIED PRODUCTS|INSTALLATION OF CCTV AND ALLIED PRODUCTS",
            "LIBRARIES, ARCHIVES, MUSEUMS AND OTHER CULTURAL ACTIVITIES|LIBRARIES, ARCHIVES, MUSEUMS AND OTHER CULTURAL ACTIVITIES",
            "MODELING SERVICES|MODELING SERVICES",
            "ORGANISE DANCE CLASS SERVICES|ORGANISE DANCE CLASS SERVICES",
            "PAINTING SERVICES|PAINTING SERVICES",
            "PARKS AND RECREATION SERVICES|PARKS AND RECREATION SERVICES",
            "PHOTOGRAPHY SERVICES|PHOTOGRAPHY SERVICES",
            "SALE OF SPORTS EQUIPMENT|SALE OF SPORTS EQUIPMENT",
            "SPORT PROMOTION SERVICES|SPORT PROMOTION SERVICES",
            "SPORT ACTIVITIES AND AMUSEMENT AND RECREATION ACTIVITIES|SPORT ACTIVITIES AND AMUSEMENT AND RECREATION ACTIVITIES",
            "STRESS MANAGEMENT SERVICES|STRESS MANAGEMENT SERVICES",
            "VIDEO CD RENTAL SERVICES|VIDEO CD RENTAL SERVICES"
        ];
    }

    else if (s1.value == "AGRICULTURE FORESTRY & FISHING") {
        optionArr = [
            "|Select Classification 2",
            "ANIMAL HUSBANDRY SERVICES|ANIMAL HUSBANDRY SERVICES",
            "AQUARIUM SERVICES|AQUARIUM SERVICES",
            "AVIARY SERVICES|AVIARY SERVICES",
            "CROP AND ANIMAL PRODUCTION,HUNTING AND RELATED SERVICES ACTIVITIES|CROP AND ANIMAL PRODUCTION,HUNTING AND RELATED SERVICES ACTIVITIES",
            "FISH FARMING/AQUACULTURE|FISH FARMING/AQUACULTURE",
            "FISHING & AQUACULTURE|FISHING & AQUACULTURE",
            "FOOD PRODUCTION AND PROCESSING SERVICES|FOOD PRODUCTION AND PROCESSING SERVICES",
            "FORESTRY & LOGGING|FORESTRY & LOGGING",
            "GARDENING SERVICES|GARDENING SERVICES",
            "HONEY PROCESSING|HONEY PROCESSING",
            "HORTICULTURAL SERVICES|HORTICULTURAL SERVICES",
            "KENNEL SERVICES|KENNEL SERVICES",
            "LIVESTOCK FEEDS PRODUCTION AND DISTRIBUTION|LIVESTOCK FEEDS PRODUCTION AND DISTRIBUTION",
            "LIVESTOCK MANAGEMENT SERVICES|LIVESTOCK MANAGEMENT SERVICES",
            "MILLING AND GRINDING SERVICES|MILLING AND GRINDING SERVICES",
            "PIGGERY SERVICES|PIGGERY SERVICES",
            "POULTRY SERVICES|POULTRY SERVICES",
            "SALE OF AGRICULTURAL PRODUCE|SALE OF AGRICULTURAL PRODUCE",
            "SALE OF AGRICULTURAL TOOLS, MACHINE & ALLIED PRODUCTS|SALE OF AGRICULTURAL TOOLS, MACHINE & ALLIED PRODUCTS",
            "SALE OF ANIMALS|SALE OF ANIMALS",
            "SALE OF DIARY PRODUCTS|SALE OF DIARY PRODUCTS",
            "SALE OF GROCERIES|SALE OF GROCERIES"
        ];
    }

    else if (s1.value == "COMMUNITY BASED ASSOCIATION") {
        optionArr = [
            "|Select Classification 2",
            "COMMUNITY BASED ASSOCIATION|COMMUNITY BASED ASSOCIATION",
            "COMMUNITY BASED ASSOCIATION|COMMUNITY BASED ASSOCIATION"
        ];
    }

    else if (s1.value == "CULTURAL BASED ASSOCIATION") {
        optionArr = [
            "|Select Classification 2",
            "CULTURAL BASED ASSOCIATION|CULTURAL BASED ASSOCIATION",
            "CULTURAL BASED ASSOCIATION|CULTURAL BASED ASSOCIATION",
            "CULTURAL BASED ASSOCIATION|CULTURAL BASED ASSOCIATION"
        ];
    }

    else if(s1.value == "CONSTRUCTION") {
        optionArr = [
            "|Select Classification 2",
            "BOAT AND CANOE CONSTRUCTION|BOAT AND CANOE CONSTRUCTION",
            "BRICKLAYING/MASONARY SERVICES|BRICKLAYING/MASONARY SERVICES",
            "BUILDING WORKS|BUILDING WORKS",
            "CARPENTRY/UPHOLSTERY SERVICES|CARPENTRY/UPHOLSTERY SERVICES",
            "CIVIL ENGINEERING|CIVIL ENGINEERING",
            "CONSTRUCTION OF BUILDINGS|CONSTRUCTION OF BUILDINGS",
            "GLASS WORKS|GLASS WORKS",
            "MECHANICAL WORKS|MECHANICAL WORKS",
            "METAL WORKS|METAL WORKS",
            "SPECIALIZED CONSTRUCTION ACTIVITIES|SPECIALIZED CONSTRUCTION ACTIVITIES",
            "STEEL WORKS SERVICES|STEEL WORKS SERVICES",
            "SUPPLY, SALE AND DISTRIBUTION OF BUILDING MATERIALS|SUPPLY, SALE AND DISTRIBUTION OF BUILDING MATERIALS"
        ];
    }

    else if(s1.value == "EDUCATION") {
        optionArr = [
            "|Select Classification 2",
            "APPRENTICESHIP AND TRAINING SERVICES|APPRENTICESHIP AND TRAINING SERVICES",
            "BUSINESS SUPPORT/DEVELOPMENT SERVICES|BUSINESS SUPPORT/DEVELOPMENT SERVICES",
            "CURRICULUM PLANNING/DEVELOPMENT|CURRICULUM PLANNING/DEVELOPMENT",
            "EDUCATION|EDUCATION",
            "EDUCATIONAL SERVICES AND CONSULTANCY|EDUCATIONAL SERVICES AND CONSULTANCY",
            "FEASIBILITY STUDIES|FEASIBILITY STUDIES",
            "GUIDANCE AND COUNSELING SERVICES|GUIDANCE AND COUNSELING SERVICES",
            "ICT TRAINING AND CONSULTANCY|ICT TRAINING AND CONSULTANCY",
            "LIBRARY SERVICES|LIBRARY SERVICES",
            "MONTESSORI SUPPLIES|MONTESSORI SUPPLIES",
            "MONTESSORI TRAINING|MONTESSORI TRAINING",
            "OPERATE BIBLE COLLEGE|OPERATE BIBLE COLLEGE",
            "OPERATE COMPUTER TRAINING SCHOOL|OPERATE COMPUTER TRAINING SCHOOL",
            "OPERATE CRÈCHE AND DAY CARE|OPERATE CRÈCHE AND DAY CARE",
            "OPERATE ISLAMIC SCHOOL|OPERATE ISLAMIC SCHOOL",
            "OPERATE NURSERY AND PRIMARY SCHOOL|OPERATE NURSERY AND PRIMARY SCHOOL",
            "OPERATE PRIMARY AND SECONDARY SCHOOL|OPERATE PRIMARY AND SECONDARY SCHOOL",
            "ORGANIZING CONFERENCES|ORGANIZING CONFERENCES",
            "ORGANIZING SEMINARS/SYMPOSIUMS|ORGANIZING SEMINARS/SYMPOSIUMS",
            "PUBLICATION OF LAW REPORTS AND JOURNALS|PUBLICATION OF LAW REPORTS AND JOURNALS",
            "TEACHERS RECRUITMENT|TEACHERS RECRUITMENT",
            "VOCATIONAL EDUCATION AND TRAINING SERVICES|VOCATIONAL EDUCATION AND TRAINING SERVICES"
        ];
    }

    else if(s1.value == "FAITH BASED ASSOCIATION") {
        optionArr = [
            "|Select Classification 2",
            "CHURCH|CHURCH",
            "CHURCH|CHURCH",
            "CHURCHES|CHURCHES",
            "IT OTHERS|IT OTHERS",
            "IT OTHERS|IT OTHERS",
            "MOSQUE|MOSQUE",
            "MOSQUES|MOSQUES",
            "MOSQUES|MOSQUES"
        ];
    }

    else if(s1.value == "FINANCIAL AND INSURANCE ACTIVITIES") {
        optionArr = [
            "|Select Classification 2",
            "ACCOUNTING / AUDITING CONSULTANCY|ACCOUNTING / AUDITING CONSULTANCY",
            "ACCOUNTING / AUDITING, TAXATION AND FINANCIAL MANAGEMENT  CONSULTANCY|ACCOUNTING / AUDITING, TAXATION AND FINANCIAL MANAGEMENT  CONSULTANCY",
            "ACTIVITIES AUXILIARY TO FINANCIAL SERVICES AND INSURANCE ACTIVITIES|ACTIVITIES AUXILIARY TO FINANCIAL SERVICES AND INSURANCE ACTIVITIES",
            "FINANCIAL CONSULTANCY|FINANCIAL CONSULTANCY",
            "FINANCIAL SERVICES ACTIVITIES, EXCEPT INSURANCE AND PENSION FUNDING|FINANCIAL SERVICES ACTIVITIES, EXCEPT INSURANCE AND PENSION FUNDING",
            "FORENSIC ACCOUNTING SERVICES|FORENSIC ACCOUNTING SERVICES",
            "INSURANCE, REINSURANCE AND PENSION FUNDING, EXCEPT COMPULSORY SOCIAL SECURITY|INSURANCE, REINSURANCE AND PENSION FUNDING, EXCEPT COMPULSORY SOCIAL SECURITY",
            "PRIVATE EQUITY FUND|PRIVATE EQUITY FUND"
        ];
    }

    else if(s1.value == "FOUNDATION BASED ASSOCIATION") {
        optionArr = [
            "|Select Classification 2",
            "FOUNDATION BASED ASSOCIATION|FOUNDATION BASED ASSOCIATION",
            "FOUNDATION BASED ASSOCIATION|FOUNDATION BASED ASSOCIATION",
        ];
    }

    else if(s1.value == "HUMAN HEALTH AND SOCIAL WORK ACTIVITIES") {
        optionArr = [
            "|Select Classification 2",
            "AMBULANCE SERVICES|AMBULANCE SERVICES",
            "BEAUTY AND SALON SERVICES|BEAUTY AND SALON SERVICES",
            "CHEMIST/NURSING HOME|CHEMIST/NURSING HOME",
            "DENTAL PRACTICE AND SERVICES|DENTAL PRACTICE AND SERVICES",
            "FUMIGATION AND PEST CONTROL SERVICES|FUMIGATION AND PEST CONTROL SERVICES",
            "GYMNASIUM SERVICES|GYMNASIUM SERVICES",
            "HUMAN HEALTH ACTIVITIES|HUMAN HEALTH ACTIVITIES",
            "MAKE UP AND MAKEOVER SERVICES|MAKE UP AND MAKEOVER SERVICES",
            "OPERATE COMMUNITY HEALTH CARE CENTRE|OPERATE COMMUNITY HEALTH CARE CENTRE",
            "OPERATE HOSPITAL / CLINIC|OPERATE HOSPITAL / CLINIC",
            "OPERATE MATERNITY CLINIC|OPERATE MATERNITY CLINIC",
            "OPTICAL SERVICES|OPTICAL SERVICES",
            "PATENT /MEDICINE SERVICES|PATENT /MEDICINE SERVICES",
            "PEDICURE  AND MANICURE SERVICES|PEDICURE  AND MANICURE SERVICES",
            "PERFUMERY SERVICES|PERFUMERY SERVICES",
            "PHYSIOTHERAPY SERVICES|PHYSIOTHERAPY SERVICES",
            "PUBLIC CONVENIENCE SERVICES|PUBLIC CONVENIENCE SERVICES",
            "RESIDENTIAL CARE ACTIVITIES|RESIDENTIAL CARE ACTIVITIES",
            "SPA TREATMENT SERVICES|SPA TREATMENT SERVICES",
            "SALE OF VETERINARY EQUIPMENT AND DRUGS|SALE OF VETERINARY EQUIPMENT AND DRUGS",
            "SALES AND SUPPLY OF HOSPITAL OPTICAL AND LABORATORY EQUIPMENT|SALES AND SUPPLY OF HOSPITAL OPTICAL AND LABORATORY EQUIPMENT",
            "SOCIAL WORK ACTIVITIES WITHOUT ACCOMMODATION|SOCIAL WORK ACTIVITIES WITHOUT ACCOMMODATION",
            "TRADITIONAL MEDICINE|TRADITIONAL MEDICINE",
            "VETERINARY SERVICES|VETERINARY SERVICES"
        ];
    }

    else if(s1.value == "INFORMATION AND COMMUNICATION") {
        optionArr = [
            "|Select Classification 2",
            "ADVERTISING AND MARKETING SERVICES|ADVERTISING AND MARKETING SERVICES",
            "BULK SMS SERVICES|BULK SMS SERVICES",
            "CINEMATOGRAPHY / THEATERS SERVICES|CINEMATOGRAPHY / THEATERS SERVICES",
            "COMPUTER PROGRAMMING, CONSULTANCY AND RELATED ACTIVITIES|COMPUTER PROGRAMMING, CONSULTANCY AND RELATED ACTIVITIES",
            "GRAPHIC DESIGNING|GRAPHIC DESIGNING",
            "INFORMATION SERVICE ACTIVITIES|INFORMATION SERVICE ACTIVITIES",
            "MOTION PICTURE, VIDEO AND TELEVISION PROGRAMME PRODUCTION, SOUND RECORDING AND MUSIC PUBLISHING ACTIVITIES|MOTION PICTURE, VIDEO AND TELEVISION PROGRAMME PRODUCTION, SOUND RECORDING AND MUSIC PUBLISHING ACTIVITIES",
            "NETWORKING SERVICES|NETWORKING SERVICES",
            "PROGRAMMIMG AND BROADCASTING ACTIVITIES|PROGRAMMIMG AND BROADCASTING ACTIVITIES",
            "PUBLISHING ACTIVITIES|PUBLISHING ACTIVITIES",
            "SOFTWARE DEVELOPMENT, WEB DESIGN AND INTRANET DEVELOPMENT|SOFTWARE DEVELOPMENT, WEB DESIGN AND INTRANET DEVELOPMENT",
            "SUPPLY OF HARDWARE|SUPPLY OF HARDWARE",
            "TELECOMMUNICATIONS|TELECOMMUNICATIONS"
        ];
    }

    else if(s1.value == "MANUFACTURING") {
        optionArr = [
            "|Select Classification 2",
            "ALUMINUM MANUFACTURING, WORKS, SALES AND FITTINGS|ALUMINUM MANUFACTURING, WORKS, SALES AND FITTINGS",
            "ELECTRICITY,GAS,STREAM & AIR CONDITIONING SUPPLY|ELECTRICITY,GAS,STREAM & AIR CONDITIONING SUPPLY",
            "LEATHER WORKS/TANNERY SERVICES|LEATHER WORKS/TANNERY SERVICES",
            "MANUFACTURE OF BASIC METALS|MANUFACTURE OF BASIC METALS",
            "MANUFACTURE OF BASIC PHARMACEUTICAL PRODUCTS AND PHARMACEUTICAL PREPARATIONS|MANUFACTURE OF BASIC PHARMACEUTICAL PRODUCTS AND PHARMACEUTICAL PREPARATIONS",
            "MANUFACTURE OF BEVERAGES|MANUFACTURE OF BEVERAGES",
            "MANUFACTURE OF CHEMICALS AND CHEMICAL PRODUCTS|MANUFACTURE OF CHEMICALS AND CHEMICAL PRODUCTS",
            "MANUFACTURE OF COKE AND REFINED PETROLEUM PRODUCTS|MANUFACTURE OF COKE AND REFINED PETROLEUM PRODUCTS",
            "MANUFACTURE OF COMPUTER, ELECTRONIC AND OPTICAL PRODUCTS|MANUFACTURE OF COMPUTER, ELECTRONIC AND OPTICAL PRODUCTS",
            "MANUFACTURE OF ELECTRICAL EQUIPMENT|MANUFACTURE OF ELECTRICAL EQUIPMENT",
            "MANUFACTURE OF FABRICATED METAL PRODUCTS, EXCEPT MACHINERY AND EQUIPMENT|MANUFACTURE OF FABRICATED METAL PRODUCTS, EXCEPT MACHINERY AND EQUIPMENT",
            "MANUFACTURE OF FOOD PRODUCTS|MANUFACTURE OF FOOD PRODUCTS",
            "MANUFACTURE OF FURNITURE|MANUFACTURE OF FURNITURE",
            "MANUFACTURE OF LEATHER AND RELATED PRODUCTS|MANUFACTURE OF LEATHER AND RELATED PRODUCTS",
            "MANUFACTURE OF MACHINERY AND EQUIPMENT N.E,C|MANUFACTURE OF MACHINERY AND EQUIPMENT N.E,C",
            "MANUFACTURE OF MOTOR VEHICLES, TRAILERS AND SEMI-TRAILERS|MANUFACTURE OF MOTOR VEHICLES, TRAILERS AND SEMI-TRAILERS",
            "MANUFACTURE OF OTHER NON-METALLIC MATERIAL PRODUCTS|MANUFACTURE OF OTHER NON-METALLIC MATERIAL PRODUCTS",
            "MANUFACTURE OF OTHER TRANSPORT EQUIPMENT|MANUFACTURE OF OTHER TRANSPORT EQUIPMENT",
            "MANUFACTURE OF PAPER AND PAPER PRODUCTS|MANUFACTURE OF PAPER AND PAPER PRODUCTS",
            "MANUFACTURE OF RUBBER AND PLASTIC PRODUCTS|MANUFACTURE OF RUBBER AND PLASTIC PRODUCTS",
            "MANUFACTURE OF TEXTILES|MANUFACTURE OF TEXTILES",
            "MANUFACTURE OF TOBACCO PRODUCTS|MANUFACTURE OF TOBACCO PRODUCTS",
            "MANUFACTURE OF WEARING APPAREL|MANUFACTURE OF WEARING APPAREL",
            "MANUFACTURE OF WOOD AND OF PRODUCTS OF WOOD AND COOK,EXPECT FURNITURE|MANUFACTURE OF WOOD AND OF PRODUCTS OF WOOD AND COOK,EXPECT FURNITURE","MANUFACTURE OF ARTICLE OF STRAW AND PLAITING MATERIAL|MANUFACTURE OF ARTICLE OF STRAW AND PLAITING MATERIAL",
            "MANUFACTURING OF CANDLES AND ASSOCIATED PRODUCTS|MANUFACTURING OF CANDLES AND ASSOCIATED PRODUCTS",
            "MANUFACTURING OF PLASTIC PRODUCTS|MANUFACTURING OF PLASTIC PRODUCTS",
            "OTHER MANUFACTURING|OTHER MANUFACTURING",
            "PRINTING AND REPRODUCTION OF RECORDED MEDIA|PRINTING AND REPRODUCTION OF RECORDED MEDIA",
            "PRODUCTION AND SALE OF BOTTLED AND PACKED WATER|PRODUCTION AND SALE OF BOTTLED AND PACKED WATER",
            "PRODUCTION AND SALE OF TILES AND CERAMIC PRODUCTS|PRODUCTION AND SALE OF TILES AND CERAMIC PRODUCTS",
            "PRODUCTION AND SALE OF  POLYTHENE BAGS|PRODUCTION AND SALE OF  POLYTHENE BAGS",
            "PRODUCTION AND SALE OF COOKING OR EDIBLE OIL|PRODUCTION AND SALE OF COOKING OR EDIBLE OIL",
            "PRODUCTION, SUPPLY, SALE AND INSTALLATION OF ELECTRICAL AND ELECTRONIC EQUIPMENT|PRODUCTION, SUPPLY, SALE AND INSTALLATION OF ELECTRICAL AND ELECTRONIC EQUIPMENT",
            "REPAIR AND INSTALLATION OF MACHINERY AND EQUIPMENT|REPAIR AND INSTALLATION OF MACHINERY AND EQUIPMENT",
            "SALE AND MANUFACTURING COSMETICS|SALE AND MANUFACTURING COSMETICS",
            "SALE AND MANUFACTURING OF CARPETS|SALE AND MANUFACTURING OF CARPETS",
            "SALE AND PRODUCTION OF FOOT WARES|SALE AND PRODUCTION OF FOOT WARES"
        ];
    }

    else if(s1.value == "MINING AND QUARRYING") {
        optionArr = [
            "|Select Classification 2",
            "EXTRACTION OF CRUDE PETROLEUM AND NATURAL GAS|EXTRACTION OF CRUDE PETROLEUM AND NATURAL GAS",
            "GEOSCIENCES SERVICES|GEOSCIENCES SERVICES",
            "MINING SUPPORT SERVICES ACTIVITIES|MINING SUPPORT SERVICES ACTIVITIES",
            "MINING AND GRINDING SERVICES|MINING AND GRINDING SERVICES",
            "MINING OF COAL AND LIGNITE|MINING OF COAL AND LIGNITE",
            "MINING OF METAL ORES|MINING OF METAL ORES",
            "OIL AND GAS SERVICES|OIL AND GAS SERVICES",
            "OTHER MINING AND QUARRYING|OTHER MINING AND QUARRYING"
        ];
    }

    else if(s1.value == "OTHERS") {
        optionArr = [
            "|Select Classification 2",
        ];
    }

    else if(s1.value == "POWER") {
        optionArr = [
            "|Select Classification 2",
            "ENERGY PRODUCTION|ENERGY PRODUCTION",
            "HYDRO ELECTRICAL WORK|HYDRO ELECTRICAL WORK",
            "PRODUCTION AND DISTRIBUTION OF RENEWABLE ENERGY|PRODUCTION AND DISTRIBUTION OF RENEWABLE ENERGY",
            "SOLAR ENERGY|SOLAR ENERGY",
            "SUPPLY, SALES AND SERVICES OF SOLAR EQUIPMENT AND INVERTERS|SUPPLY, SALES AND SERVICES OF SOLAR EQUIPMENT AND INVERTERS"
        ];
    }

    else if(s1.value == "PROFESSIONAL,SCIENTIFIC AND TECHNICAL ACTIVITIES") {
        optionArr = [
            "|Select Classification 2",
            "ACCOUNTING AND AUDITING CONSULTANCY|ACCOUNTING AND AUDITING CONSULTANCY",
            "ACTIVITIES OF HEAD OFFICIES;MANAGEMENT CONSULTANCY ACTIVITIES|ACTIVITIES OF HEAD OFFICIES;MANAGEMENT CONSULTANCY ACTIVITIES",
            "ADVERTISING AND MARKET RESEARCH|ADVERTISING AND MARKET RESEARCH",
            "AERONAUTIC ENGINEERING/CONSULTANCY|AERONAUTIC ENGINEERING/CONSULTANCY",
            "AGRICULTURAL ENGINEERING|AGRICULTURAL ENGINEERING",
            "ARBITRATION/MEDIATION SERVICES|ARBITRATION/MEDIATION SERVICES",
            "ARCHITECTURAL PRACTICE AND CONSULTANCY|ARCHITECTURAL PRACTICE AND CONSULTANCY",
            "ARCHITECTURAL AND ENGINEERING ACTIVITIES; TECHNICAL TESTING AND ANALYSIS|ARCHITECTURAL AND ENGINEERING ACTIVITIES; TECHNICAL TESTING AND ANALYSIS",
            "AUCTIONEERING SERVICES|AUCTIONEERING SERVICES",
            "CHEMICAL ENGINEERING SERVICES|CIVIL ENGINEERING SERVICES",
            "CIVIL ENGINEERING SERVICES|CIVIL ENGINEERING SERVICES",
            "CLINIC AND MATERNITY HOME|CLINIC AND MATERNITY HOME",
            "COMMUNITY HEALTH CENTER|COMMUNITY HEALTH CENTER",
            "COMPANY LIQUIDATION SERVICES|COMPANY LIQUIDATION SERVICES",
            "COMPANY SECRETARIAL SERVICES|COMPANY SECRETARIAL SERVICES",
            "ELECTRICAL ENGINEERING SERVICES|ELECTRICAL ENGINEERING SERVICES",
            "ENGINEERING SERVICES|ENGINEERING SERVICES",
            "HUMAN RESOURCES MANAGEMENT AND DEVELOPMENT SERVICES|HUMAN RESOURCES MANAGEMENT AND DEVELOPMENT SERVICES",
            "LABORATORY SERVICES|LABORATORY SERVICES",
            "LEGAL PRACTICE AND CONSULTANCY|LEGAL PRACTICE AND CONSULTANCY",
            "LEGAL AND ACCOUNTING ACTIVITIES|LEGAL AND ACCOUNTING ACTIVITIES",
            "LEGISLATIVE CONSULTANCY|LEGISLATIVE CONSULTANCY",
            "MANAGEMENT CONSULTANCY SERVICES|MANAGEMENT CONSULTANCY SERVICES",
            "MEDICAL PRACTICE AND CONSULTANCY|MEDICAL PRACTICE AND CONSULTANCY",
            "MIDWIFERY SERVICES|MIDWIFERY SERVICES",
            "OTHER PROFESSIONAL,SCIENTIFIC AND TECHNICAL ACTIVITIES|OTHER PROFESSIONAL,SCIENTIFIC AND TECHNICAL ACTIVITIES",
            "PHARMACEUTICAL SERVICES|PHARMACEUTICAL SERVICES",
            "PHYSIOTHERAPY SERVICES|PHYSIOTHERAPY SERVICES",
            "QUANTITY SURVEYING|QUANTITY SURVEYING",
            "RADIOGRAPHY AND GENERAL BODY LANGUAGE SERVICES|RADIOGRAPHY AND GENERAL BODY LANGUAGE SERVICES",
            "SCIENTIFIC RESEARCH AND DEVELOPMENT|SCIENTIFIC RESEARCH AND DEVELOPMENT",
            "TAX CONSULTANCY|TAX CONSULTANCY",
            "VERTERINARY ACTIVITIES|VERTERINARY ACTIVITIES"
        ];
    }

    else if(s1.value == "PUBLIC ADMINISTRATION AND DEFENCE;DEFENCE, COMPULSORY SOCIAL SECURITY") {
        optionArr = [
            "|Select Classification 2",
            "PUBLIC ADMINISTRATION AND DEFENCE; COMPLUSORY SOCIAL SECURITY|PUBLIC ADMINISTRATION AND DEFENCE; COMPLUSORY SOCIAL SECURITY"
        ];
    }

    else if(s1.value == "REAL ESTATE ACTIVITIES") {
        optionArr = [
            "|Select Classification 2",
            "ENVIRONMENTAL AND LANDSCAPING SERVICES|ENVIRONMENTAL AND LANDSCAPING SERVICES",
            "ESTATE AGENCY|ESTATE AGENCY",
            "ESTATE SURVEYING AND VALUATION|ESTATE SURVEYING AND VALUATION",
            "ESTATE AND FACILITY MANAGEMENT|ESTATE AND FACILITY MANAGEMENT",
            "PROJECT MANAGEMENT SERVICES|PROJECT MANAGEMENT SERVICES",
            "PROPERTY DEVELOPMENT SERVICES|PROPERTY DEVELOPMENT SERVICES",
            "PROPERTY MANAGEMENT SERVICES|PROPERTY MANAGEMENT SERVICES",
            "REAL ESTATE ACTIVITIES|REAL ESTATE ACTIVITIES",
            "TOWN PLANNING SERVICES|TOWN PLANNING SERVICES"
        ];
    }

    else if(s1.value == "REPAIRS OF MOTORVEHICLES AND MOTORCYCLES") {
        optionArr = [
            "|Select Classification 2",
            "AUTOMOBILE REPAIRS/MECHANICAL SERVICES|AUTOMOBILE REPAIRS/MECHANICAL SERVICES",
            "PANEL BEATING/CAR SPRAYING SERVICE|PANEL BEATING/CAR SPRAYING SERVICE",
            "SALE OF AUTOMOBILE SPARE PARTS|SALE OF AUTOMOBILE SPARE PARTS",
            "SALE OF ENGINEERING EQUIPMENT, MACHINERY AND OTHER HARDWARE|SALE OF ENGINEERING EQUIPMENT, MACHINERY AND OTHER HARDWARE",
            "SALE OF MOTOR VEHICLE, MOTORCYCLES AND OTHER AUTOMOBILE PRODUCTS|SALE OF MOTOR VEHICLE, MOTORCYCLES AND OTHER AUTOMOBILE PRODUCTS"
        ];
    }

    else if(s1.value == "SOCIAL CLUBS BASED ASSOCIATION") {
        optionArr = [
            "|Select Classification 2",
            "SOCIAL CLUBS BASED ASSOCIATION|SOCIAL CLUBS BASED ASSOCIATION",
            "SOCIAL CLUBS BASED ASSOCIATION|SOCIAL CLUBS BASED ASSOCIATION",
            "SOCIAL CLUBS BASED ASSOCIATION|SOCIAL CLUBS BASED ASSOCIATION"
        ];
    }

    else if(s1.value == "SPORTING BASED ASSOCIATION") {
        optionArr = [
            "|Select Classification 2",
            "SPORTING BASED ASSOCIATION|SPORTING BASED ASSOCIATION",
            "SPORTING BASED ASSOCIATION|SPORTING BASED ASSOCIATION",
            "SPORTING BASED ASSOCIATION|SPORTING BASED ASSOCIATION"
        ];
    }

    else if(s1.value == "TRANSPORTATION") {
        optionArr = [
            "|Select Classification 2",
            "AIR TRANSPORT|AIR TRANSPORT",
            "LAND TRANSPORT AND TRANSPORT VIA PIPELINES|LAND TRANSPORT AND TRANSPORT VIA PIPELINES",
            "POSTAL AND COURIER ACTIVITIES|POSTAL AND COURIER ACTIVITIES",
            "RAIL AND TRAMP SERVICES|RAIL AND TRAMP SERVICES",
            "ROAD TRANSPORTATION SERVICES|ROAD TRANSPORTATION SERVICES",
            "SEA TRANSPORT|SEA TRANSPORT",
            "TRUCK AND HAULAGE SERVICES|TRUCK AND HAULAGE SERVICES",
            "WAREHOUSING AND SUPPORT ACTIVITIES FOR TRANPORTATION|WAREHOUSING AND SUPPORT ACTIVITIES FOR TRANPORTATION",
            "WATER TRANSPORT|WATER TRANSPORT"
        ];
    }

    else if(s1.value == "WATERSUPPLY,SEWERAGE,WASTEMANAGEMENT AND REMEDIATION ACTIVITIES") {
        optionArr = [
            "|Select Classification 2",
            "BOREHOLE DRILLING AND WATER WORKS|BOREHOLE DRILLING AND WATER WORKS",
            "CLEANING/WASTE DISPOSAL SERVICES|CLEANING/WASTE DISPOSAL SERVICES",
            "INDUSTRIAL CLEANING SERVICES|INDUSTRIAL CLEANING SERVICES",
            "LAUNDRY AND DRY CLEANING SERVICES|LAUNDRY AND DRY CLEANING SERVICES",
            "REMEDIATION ACTIVITIES AND OTHER WASTE MANAGEMENT SERVICES|REMEDIATION ACTIVITIES AND OTHER WASTE MANAGEMENT SERVICES",
            "SEWERAGE|SEWERAGE",
            "WASTE COLLECTION, TREATMENT AND DISPOSAL ACTIVITIES: MATERIAL RECOVERY|WASTE COLLECTION, TREATMENT AND DISPOSAL ACTIVITIES: MATERIAL RECOVERY",
            "WATER COLLECTION TREATMENT AND SUPPLY|WATER COLLECTION TREATMENT AND SUPPLY"
        ];
    }

    else if (s1.value == "WHOLESALE AND RETAIL TRADE;REPAIR OF MOTOR VEHICLES AND MOTOR VEHICLES AND MOTORCYCLES") {
        optionArr = [
            "|Select Classification 2",
            "DEAL IN GENERAL GOODS AND MANUFACTURERS REPRESENTATIVES|DEAL IN GENERAL GOODS AND MANUFACTURERS REPRESENTATIVES",
            "IMPORT AND EXPORT OF GENERAL GOODS|IMPORT AND EXPORT OF GENERAL GOODS",
            "OPERATE DEPARTMENTAL STORES|OPERATE DEPARTMENTAL STORES",
            "OPERATE SUPERMARKETS|OPERATE SUPERMARKETS",
            "RETAIL TRADE, EXCEPT OF MOTOR VEHICLE AND MOTORCYCLES|RETAIL TRADE, EXCEPT OF MOTOR VEHICLE AND MOTORCYCLES",
            "SUPPLY AND DISTRIBUTION OF GENERAL GOODS|SUPPLY AND DISTRIBUTION OF GENERAL GOODS",
            "WHOLESALE AND RETAIL TRADE AND REPAIR OF MOTOR VECHICLES AND MOTORCYCLES|WHOLESALE AND RETAIL TRADE AND REPAIR OF MOTOR VECHICLES AND MOTORCYCLES",
            "WHOLESALE TRADE, EXCEPT OF MOTOR VEHICLE AND MOTORCYCLE|WHOLESALE TRADE, EXCEPT OF MOTOR VEHICLE AND MOTORCYCLE"
        ];
    }

    for (var option in optionArr) {
        var pair = optionArr[option].split("|");
        var newOption = document.createElement("option");
        newOption.value = pair[0];
        newOption.innerHTML = pair[1];
        s2.options.add(newOption);
    }    
}